# Model arguments
# SRIJITH YOU MADE A MISTAKE BY USING THIS INSTEAD OF 2e variant 
# model_name_or_path: /data/tir/projects/tir7/user_data/srijithr/spin_outputs/geneal_8_gpu_wSAVECKPT_final_full_SFT_L40/


model_name_or_path: /data/tir/projects/tir7/user_data/srijithr/spin_outputs/geneal_8_gpu_wSAVECKPT_final_full_SFT_L40/checkpoint-1600/
# model_name_or_path: microsoft/phi-1
# openai-community/gpt2
# model_revision: 

# Data training arguments
dataset_mixer:
  #HuggingFaceH4/ultrafeedback_binarized: 1.0
  UCLA-AGI/SPIN_iter0: 1.0

use_local_dataset : true
local_dataset_mixer:
  - /home/srijithr/iterative-alignment/SPIN_implementation/data/gen_using_iter0_3e_variant/synthetic_train_iter0.json
  - /home/srijithr/iterative-alignment/SPIN_implementation/data/gen_using_iter0_2e_variant/loser_0.jsonl


dataset_splits:
- train
- test
preprocessing_num_workers: 8

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: true
hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-7
log_level: info
logging_steps: 2
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
optim: rmsprop
output_dir: /data/tir/projects/tir7/user_data/srijithr/spin_outputs
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
# save_strategy: "epoch" steps
save_strategy: "epoch"
# save_steps: 200
save_total_limit: null
seed: 42
warmup_ratio: 0.1

# # Added to change default arguments
# # output_dir: /data/tir/projects/tir7/user_data/srijithr/spin_outputs
run_name: you_forgot_to_set_name_your_run
# use_peft : true
report_to: wandb
# # lora_target_modules: 'k_proj q_proj v_proj'
# # lora_target_modules: 'k_proj q_proj v_proj'
# # lora_modules_to_save:
# # - q_proj
# # - k_proj
# # - v_proj
# lora_target_modules:
# - q_proj
# - k_proj
# - v_proj
# # Below are hard-coded
# # bias: "none"
# # task_type: "CAUSAL_LM"